### ISSUE TITLE
Table 2 and page 4 have different names for the controllers

### ISSUE THREAD

**Issue by JJ** [salem23/ConfofGames2019#24]
The former uses a "G" where the other does not.
Also, "V" is used when BLX-alpha is introduced. I don't see any relationship...

**Comment by JJ** [comment]
In general, we need to univy names. GPSVAE, VGPSAE and VAGPSE are all used.

**Comment by salem23** [comment]
We have two main controllers 
GPS based and varying alpha GPS based
E is for every generation
L for the last one 
5  when the GPS is used  every 5 gen

**Comment by JJ** [comment]
OK, but we should always use the same order... 
Also use {\sf } instead of $$. It plays ugly tricks on the letter separation.
