### ISSUE TITLE
Draw a table with controller output

### ISSUE THREAD

**Issue by JJ** [salem23/ConfofGames2019#29]
Using [this paper](https://www.researchgate.net/publication/323619574_Evolving_a_TORCS_Modular_Fuzzy_Driver_Using_Genetic_Algorithms) if it's the still the same, but also putting real output values.

**Comment by salem23** [comment]
You mean target speeds and steering?
you want the whole values of a race??
It 's a lot of data to plot

**Comment by JJ** [comment]
Not really. In that paper you use TS1 and so on, and then put the values. It's just to put the set of rules in a table, like the one I put there.

**Comment by salem23** [comment]
I have updated tables with rules of TS and S(steer) in section3
