### ISSUE TITLE
Rev 3 Comment 12 - on using different combinations of controllers.

### ISSUE THREAD

**Issue by salem23** [salem23/ConfofGames2019#52]
Re Table 3:
- as far as I understand, the controllers in the respective subtables compete against each other. I think you should try to see what happens if there are different combinations of controllers. Because now, there are 5 relatively similar controllers per experiment - I am unsure what effects this has on the race - it might just block other controllers off?

**Comment by JJ** [comment]
Rather unclear to me what it means here. I'll try to do my best to answer, but any help is appreciated.
